---
title: 'Educational Pairings and Fertility Decline in Brazil: An Analysis Through Cohort Fertility'
  
output: 
  word_document:
    reference: reference.docx
    
bibliography: bibliography.bib
biblio-style: authoryear
csl: comparative-population-studies.csl
---

# Introduction

Brazil perceived a steep drop on its total fertility levels from 1960s [@merrick_berquo1983] and nowadays exhibits below replacement fertility levels [@berquo_cavenaghi2014;@castanheira_kohler2015;@lima_etal2018;@rios-neto_etal2018]. The Brazilian fertility transition occured in a heterogeneous way among the country's regions and social strata in terms of pace and beggining of transition [@potter_etal2010]. In this sense, the higher status social strata of urban and industrialized areas already practiced birth control before the generalized decline of fertility in the 1960s [@merrick_berquo1983;@guzman_rodriguez1993], a behaviour that rapidly spread towards the lower status socioeconomic groups [@carvalho_wong1992;@perpetuo_wanjman1998;@berquo_cavenaghi2014]

Several factors explain the converging fertility regimes of social groups in Brazil, industrialization and urbanization, changes in labor market and productive structures, reduction of infant mortality rates, higher access to formal schooling followed by a higher presence of females in the labor market, reduction of rural workers, changes in gender relations, expansion of consume society and communication systems among other factors related to socioeconomic and technological development [@merrick_berquo1983; @paiva1987;@faria1989;@oliveira1989;@lam_etal1992;@alves1994;@martine1996;@potter_etal2002;@castanheira_kohler2017;@rios-neto_etal2018]. Different transition paces were, however, observed among regions and social strata. Lower income and lower educated social groups from North and Northeast regions, for example, only started its fertility transition process in the decade of 1980 at an accelerated pace whereas Southern regions already observed a declining fertility trend in 1960 decade [@potter_etal2002;@potter_etal2010].

While the country observed a declining fertility trend it was already experiencing an expansion of its educational systems. This resulted in the increase of population proportions attending formal schooling [@romanelli1986]. As documented in the literature, education has a direct influence in reproductive behavior of population since it has a key hole in family formation, human capital development, female participation in labor force, adoption of contraceptive methods, definition of time of entry in motherhood, reduction of gender inequalities and in determining assortative mating patterns [@martin_juarez1995;@jejeebhoy1995;@mcdonald2000;@messina2002;@arriagada2002, schwartz_mare2005, esping-andersen2009]. Therefore, formal education enrolment expansion in Brazil corroborated to changes in reproductive behavior in the country in terms of level and pattern of fertility trends [@merrick_berquo1983;@lam_etal1992;@neto_guimaraes2013;@berquo_cavenaghi2014;@lima_etal2018;@rios-neto_etal2018]. Also, it influenced the assortative mating patterns in the country [@esteve_mcaa2007;@ribeiro_silva2009;@longo2011]. 

Nevertheless, persisting inequalities in income distribution did not allow for further reductions in educational disparities among social groups and regions [@wood_carvalho1988;@silva_hasenbalg2000]. In this sense, educational inequalities became part of the country's social structure and have broad effects on the fertility level [@berquo_cavenaghi2014] and age-specific schedule [@lima_etal2018].

Further, recent trends in assorative mating and family settings led to new family arrangements as results of changing family norms [@berquo1998]. Therefore, new assortative mating patterns [@esteve_mcaa2007;@ribeiro_silva2009], fertility postponement [@bixby_etal2009;@miranda-ribeiro_etal2016;@rios-neto_etal2018], educational fertility differentials and below replacement fertility [@berquo_cavenaghi2014;@lima_etal2018] are part of the new Brazilian demographic scenario.

This complexity of elements acting in demographic processes of recent periods require novel tools and perspectives of evaluation. Two approaches in fertility studies are proeminent: cohort analysis and male-perspective in reproductive behavior. Cohort fertility analysis have the advantage of considering simultaneous experiences of different social groups along their life courses which may cause distortions in period analysis [@ryder1965;@ryder1990;@bongaarts_feeney1998;@bongaarts_sobotka2012;@sobotka_etal2012]. Moreover, the evaluation of male fertility trends and influences in the couple's reproductive decision making are being used as a resource to tackle recent demographic scenarios [@thomson1997;@oliveira2007;@vanbavel2017;@nitsche_etal2018], such as increasing hipogamy [@esteve_etal2012_1;@esteve_etal2016] and changing gender norms within and out of family  [@mcdonald2000;@esping-andersen2009]. This two approaches, however, have not been explored in Brazilian fertility studies [@lam_etal1992;@oliveira2007;@reher_requena2014]. 

Brazilian statistics lacks longitudinal studies to track demographic changes of the country along time. Hence, cohort studies based on census data are alternatives to evaluate social trends of social groups that experience similar events throughout time without requiring complex statistical manipulation [@ryder1965;@bongaarts_sobotka2012;@sobotka_etal2012]. In relation to cohort fertility analysis, this methodological approach permits the reconstruction and analysis of reproductive trends of cohorts that experienced the processes of intense urbanization, industrialization and schooling expansion of the country. This trends provide important subsidies for the evaluation of next generation's fertility patterns.

This study aims to evaluate cohort fertility of Brazilian educational pairings through the period of the country's fertility transition. We evaluate the cohort fertility of women within specific educational pairings in order to take male's educational influence on couple's reproductive decision making. We will also look for regional disparities, taking in account the countries persisting and historical inequalities among regions.

This work brings important discussions and contributions to Brazilian demographic analysis for many reasons. First, there are few works that evaluate cohort fertility patterns trends throughout the process of educational expansion. Also, this work recognizes the relevance of considering the partner's influence on couple's reproductive decision making [@thomson1997;@vanbavel2017]. Therefore, the evaluation of cohort trends within the analysis of the partners characteristics aims to identify changes in gender norms and family structures throughout the period of fertility transition [@pampel2011]. 

Our results show that ...

# Background

## Schooling expansion and fertility decline in Brazil

Education plays an important role in individual's human capital, life quality and decision making [@lutz2010]. Educational systems were set up as children education was perceived as a social duty and since then, schools have gained relevance in shaping individual's transition into adulthood [@aries1978].

Schooling acts as a strong determinant of reproductive behavior of women through several mechanisms [@jejeebhoy1995]. In particular, formal education influences in female entry into labor market and marriage, which changes women exposure to childbearing [@martin_juarez1995;@neels_etal2017]. Also, education provides the accomplishment of reproductive intentions through information on modern contraceptive measures and by giving support to scientific knowledge [@cleland_wilson1987;@jejeebhoy1995]. 

The massification of educational systems brings substantial indirect effects over population fertility levels. This effect is a result of increasing social costs of the maintainance of child in schools by families, cultural changes promoted by education and propagation of Western middle class values [@aries1978;@caldwell1980;@folbre1983;caldwell2006]. In addition, higher educated women show increased productive potential at the labor market, which inccurs in lower opportunity costs of childbearing than their lower educated counterparts [@becker1993;@goldin_katz2002;@goldin2006].

Therefore, the population's formal instruction is a key element in the comprehension of fertility transition timing [@guzman1991;@bongaarts2003; @chackiel_schkolnik2003]. Usually, social elites show a precursor movement of reproductive control due to their higher schooling [@cleland_wilson1987]. This behavior is then difunded to other social strata through time and marks the beginning of the generalized decline of fertility levels [@cleland_wilson1987;@bongaarts2003].

In Brazil, the fertility transition was marked by social differentials. Higher educated social groups already addopted reprodutve control methods by the time of the begining of the generalized decline  of Brazilian fertility [@merrick_berquo1983]. Throughout time, the fertility rates of different social groups converged into replacement fertility levels [@berquo_cavenaghi2014]. This was accomplished by the diffusion of modern contraceptive methods, especially female sterilization and contraceptive pill [@merrick_berquo1983; @perpetuo_wanjman1998; @martine1996;@perpetuo_wong2009]. However, the access to family planning was not even among social groups which brought negative implications to the most vulnerable social groups, which made use of health-threatening methods such as sterilization and even clandestine abortion [@martine1996;@faria1997;perpetuo_wajnman1998;perpetuo_wong2009]. 

Nowadays, educational fertility differentials manifest in terms of fertility timing - lower educated women usually exhibit younger ages of entry into motherhood [@lima_etal2018]. Thus, fertility postponement is already a reality for social elites of the country [@rios-neto_etal2018].

Compared to other educational systems in Latin America, the Brazilian educational expansion showed significant lags in schooling improvement of its population [@kang2011;@lustig_etal2013;komatsu_etal2017]. The begining of a sustained movement of educational expansion in the country only started in 1930s [@romanelli1986] with the acceleration of school enrolment [@komatsu_etal2017]. Prior to 1930, the pressure for the expansion of educational systems were restricted to minor political groups due to the rural characteristics of the country, marked by geographical disconnection of populations and an outdated agricultural productive system [@merrick_graham1981;@romanelli1986;@wood_carvalho1988]. 

The decade of 1930 was marked by a rupture with old dominant political classes of the country, which brought significant changes for the country's economy [@merrick_graham1981]. Brazil's productive model shifted from an economy based on exports of agricultural goods to an economy partially based on urban centers and industry [@merrick_graham1981;@romanelli1986]. The capitalist industrial economic model requires a mass educational system in order to succeed in terms of productive and consumption capacity [@romanelli1986]. In this sense, the change in productive model of the country resulted in a redesign of country's educational policies. The expansion of the primary education however had lower incentives than secondary or tertiary education which aimed to the new urban-industrialized economy [@romanelli1986;@kang2017;komatsu_etal2017]. The administration of primary educational systems were of responsability of states and municipalities whereas the financial resources were centralized in the federal government [@kang2011]. Therefore, urbanized regions with more resources could invest in education more than other underfunded areas and this reflects in the structural inequalities that are perceived until nowadays in the country's territory where the North-Northeast lags in socioeconomic indicators in relation to South-Southeastern regions [@merrick_graham1981;wood_carvalho1988;@barros_mendonca1995;@komatsu_etal2017]. 

Therefore, the main changes in educational policy in the period from 1930 to 1960 were aimed to prepare the population for an urban-industrial economic model. This was granted by the foundation of Ministry of Education and Health in 1931, followed by the creation of the National Institute of Pedagogy (which now is the National Institute for Educational Studies and Research "Anísio Teixeira"), the National Institute of Geography and Statistics (responsible for country's statistics and national censuses) and national services of industrial and retail learning [marcilio2014]. In 1961, the first Law of Directives and Bases of National Education, reviewed in 1971, which reinforced the obligation of basic education and set up the bases of the current educational system of the country composed by primary and secondary schooling for a compulsory instruction of population [@marcilio2014]. Thus, from 1970 to 2000, Brazil experienced relevant increases in enrolment rates in all educational levels [@figoli2006] and in the 1990s the country finally achieved universal primary schooling enrolment [@castro1998].

This educational expansion process brought also multiple changes for Brazilian females. The female schooling expansion was in the begining fomented by a sex-stratified educational system in which women received instruction for specific labor sectors such as health, hospitality and education [@besse1999]. Even though this process inccurred in labor market and, therefore, wage gender inequalities, it fostered female participation in the labor market and the translation of women from the private relm (household and family) to the public relms of the society (public spaces and labor market) [@maluf_mott1998;@azevedo_ferreira2006]. Thus, female educational expansion resulted in the reversion of male educational advantages [@beltrao_alves2009] and promoted important transformations in gender relations and social norms of the country through XX century [@itaborai2015] with increasing participation in labor markets [@scorzafave2001] and larger enrolments in secondary and tertiary education [@godinho_etal2006] .

## Assortative mating trends in Brazil

The population's assortative mating patterns are associated to the heterogeneity of social characteristics of its individuals [@blau_schwartz1997]. Hence, the opportunity of social interactions throughout unions between social groups depends on the composition of marriage markets and on the size of social groups [@kalmijn1998]. In this sense, educational composition of marriage markets are usually analysed by demographers due to some important advantages over other socioeconomic measures such as income. Education attainment is usually constant over time for adult populations (income, on the other hand is volatile) and it shapes individual's life course, preferences and professional aspirations [@warren1966;@mare1991;@kalmijn1998;@esteve_etal2012_1]. 

Schools (such as labor markets and neighborhoods) creates social networks in which union formation takes place [@warren1966;@eckland1968]. Therefore, the mass formal education system culture is one of the responsibles for non-randomness of union formation. In general, unions take place between people of similar educational levels due to closer social contact of school classes and due to shared human capital formation [@kalmijn1998]. Universities, for example, constitute the most homogamous marriage markets, since its couples usually spend most of its youth in the educational system with similar peers [@mare1991].

Educational composition changes in Brazilian demography were not only responsible for fertility decline [@lam_etal1992], but also had major effects on assortative mating patterns of the country [@ribeiro_silva2009]. Both hipogamy (couples in which females are higher educated) and hipergamy (couples in which female is lower educated) increased from 1970 to 2010, but hipogamy increased at a higher pace due to female accelerated educational gains in the period [@esteve_mcaa2007;@esteve_etal2016]. 

The prevalence of homogamous couples (couples with partners of the same educational level), on the other hand, decreased over the period [@esteve_mcaa2007;@ribeiro_silva2009]. In Brazil, this assortative mating pattern has major prevalence of lower educated social groups and its reduction is a result of the expansion of the educational system [@ribeiro_silva2009]. Also, homogamy of higher educated couples are a feature of the country's assortative mating patterns and represent a barrier to social interactions among social groups [@esteve_mcaa2007;@torche2010].   

## Reproductive decision making and family conflicts

Despite its relevant role in population reproduction, male and female interactions in fertility decision making have been analysed by few works in demography [@nitsche_etal2018]. Generally, males are usually left out of fertility demographic analysis [@oliveira_etal1994;@goldscheider_kaufman1996;@vanbavel2017]. It happens due to the lack of information on male's reproductive intentions and behavior [@schoumaker2019]. However, as women, males play a key role in family decision making of resource allocation and in family planning [@thomson1997]. Hence, the evaluation of male's characteristics in reproduction of couples gain importance in a period of changing gender relations, cultural norms, family relations and assortative mating patterns.

Over the last century, this Western trend of female schooling expansion followed by increased demand of labor force and reduced social costs of reproduction led to the first phase of the Gender Revolution [@goldscheider_etal2015]. This phase is marked by the increased participation of women in the public and institutional spheres [@goldin2006;@esping-andersen2009;@england2010]. The second phase of this revolution would be guided by an increase in male's participation in the private sphere, e. g., in household chores and childbearing [@esping-andersen2009]. An optimistic perspective of this second phase would foresee a new balance of gender relations in the future with lower constraints to female reproduction and greater commitment of partners to childbearing and domestic activities [@myrskyla_etal2011;@goldscheider_etal2015].

However, neither the greater participation in the public shpere of society and neither the larger schooling levels led to improvements in sexual division of labor [@england2010]. In Brazil, female participation in the labor market results in a double burden, especially for the most vulnerable social classes which can not afford domestic and childbearing services from the market [@guedes2015;@itaborai2016]. Moreover, this social constraints inccur in different strategies for women to conciliate their activities in the labor market with social reproduction activities (household chores and childbearing): part-time jobs [@england2010;guedes2015], abandonment of labor market [@teixeira2014] and reproductive control by modern contraception adoption to addapt to the financial and time-constraining reality [@oliveira1989]. In the higher social strata, women dedicate lower time to household chores due to the access to hospitality services in the market or to higher participation in the labor market while men of higher educational levels tend to be more active in domestic activities[@itaborai2016].

Individual's educational characteristics are fundamental in shaping the life course. It acts in the public sphere by influencing the labor market decisions and opportunities and the private sphere by providing information on family planning strategies or by empowering individuals to overcome old social and gender norms. For this reason, in a context of changing gender norms and diversifying assortative mating profiles, it is essential to consider the characteristics of both partenrs to evaluate the fertility profiles of societies [@nitsche_etal2018].

# Data and Methods

## Data

This paper uses data collected via IPUMS-International from Brazilian National Censuses of 1970, 1980, 1991, 2000 and 2010 promoted by the Brazilian Institute of Geography and Statistics (IBGE, from Prtuguese *Instituto Brasileiro de Geografia e Estatística*). We used IPUMS data because it is harmonized in time and space which make it possible the comparison of different demographic scenarios and areas without the need for compatibilization [@esteve_sobek2003;@ipums2018].

From the information and variables available at IPUMS and Brazilian censuses it was possible to identify individual socioeconomic characteristics of members of the same household. Therefore it was necessary to identify the educational level of household members, number of children ever born to women of the household and the respective partner of each household women. This identification is done through the following variables: household serial number, marital status and relationship with the household head. Using this information we paired women and their respective partners and stored their information on children ever born and educational attainment level. We used educational attainment level available in four levels at IPUMS: 1) Less than Primary, 2) Complete Primary, 3) Complete Secondary and 4) Complete Tertiary [@ipums2018]. 

Partners were chosen based on the information of marital status and household head relationship. We chose to evaluate either formal or consensual unions because cohabitation is a difunded feature in Brazil among all social strata and it accounts for a non-negligible share of observed fertility levels [@esteve_etal2012_2;@laplante_etal2015;@vieira2016]. Despite formal and consensual unions display different age-specific fertility profiles [@vieira_alves2016] and different fertility levels [@vieira2016], they do not exhibit significant differentials in terms of assortative mating patterns [@esteve_mcaa2007].

By taking the difference between census reference period and women age we could estimate cohort fertility rates (CFR) for Brazil and selected regions. We restricted female ages to the range from 40 to 69 years old and male ages to the range of 35 to 79. We considered that by 40 women would already have completed or would be close to complete their reproductive cycle. This women age ranges make it possible to reconstruct cohorts from 1901 to 1970. However, we restrict our analysis to cohorts from 1925-1969 because of data quality issues related to memory misstatements of number of children ever born for older women [@brass_etal1968] and due to data contiguity issues for this older cohorts educational groups (appendix A). For men, we chose a broader age range to increase the number of observations of couples in which they are older than women (which are the majority) and of couples in which they are younger.

Improbable and unreliable children ever born statements were also addressed prior to the estimation of CFRs. We assumed that women can bear only one living child each 18 months starting from age 12 [@moultrie_etal2013]. Thus, when the stated number of children ever born exceeded the threshold expected parity for the respective age we set its value to the maximum expected for the mother's age. More details on data quality issues are provided in appendix A.

Finally, we grouped regions into 3 groups: 1) Central-West, 2) South-Southeast and 3) North-Northeast. These groups were choosen based on shared socioeconomic characteristics and demographic characteristics of cohort fertility and assortative mating verified in previous analysis [monteiro-da-silva2019]. Thus, this grouping facilitates managing scale issues of small sample sizes in regions of lower population density and lower population counts of some particular educational groups.

## Educational pairings cohort fertility trends

Assuming the mentioned conditions and the educational groups, we may estimated cohort fertility rates for each educational pairing profile by:

$$ CFR_{F,M}^{t} = \frac{CHBORN_{F,M}^{t}} {W_{F,M}^{t}} $$
Where,

* $CFR_{F,M}^{t}$: Cohort Fertility Rates for cohorts of women born in time t with an educational attainment level F married/in-union with a partner that reached an educational attainment level M;

* $CHBORN_{F,M}^{t}$: Children Ever Born to cohorts of women born in time t with an educational attainment level F married/in-union with a partner that reached an educational attainment level M;

* $W_{F,M}^{t}$: Total number of women from the cohort born in time t with an educational attainment level F married/in-union with a partner that reached an educational attainment level M;

We computed CFRs in two ways for different methodological evaluations. First, we computed CFRs for each educational pairing of women cohorts ranging from 1925-1969 grouped in five-year age groups and educational levels LP (less than primary education completed), P (primary education completed) and S+ (secondary or tertiary education completed). The last two educational level groups were grouped in order to avoid small samples of people with higher educational attainment levels from older cohorts. 

CFR trends were then evaluated in terms of both male's and female's educational attainment levels in order to visualize each partners influence on each region fertility transition. We also computed relative differences in CFRs [@vanbavel_zeman_etal2018] between men with LP and S+ educational levels in relation to those with P educational level, controlling by female educational category as described above. Trends in relative differences among male educational categories will contribute to observe possible converging patterns of fertility transition among male's educational categories such as observed for women [@berquo_cavenaghi2014].

$$ RDiff^t_{F,M = LP-P} = \dfrac{CFR^t_{F,M = LP} - CFR^t_{F,M = P}}{CFR^t_{F,M = P}}$$

$$ RDiff^t_{F,M = S+-P} = \dfrac{CFR^t_{F,M = S+} - CFR^t_{F,M = P}}{CFR^t_{F,M = P}}$$

## CFRs decomposition

In a second moment, we computed CFR for broader year interval cohorts: 1925-39, 1940-54 and 1955-1969. Taking more cohorts in consideration made it possible to evaluate even the tertiary education influence and decompose the effects of educational expansion and changing marital profiles in fertility by comparing each cohort group. We used demographic decomposition methods [@dasgupta1993] such as performed by @yoo2014 to assess both educational pairings *composition effects* and cohort fertility *rate effects* on cohort fertility differentials ($ \Delta CFR $). 

The overall conjugal CFR for a given period T is computed by:

$$ CFR^T = \sum_i^{ep} CFR^T_{ep} P^T_{ep} $$

Further, the differences in CFR from time T1 to time T2 are given by:

$$ \Delta CFR_{12} = CFR^{T1} - CFR^{T2}  = \sum_i^{ep} CFR^{T1}_{ep} P^{T1}_{ep} - \sum_i^{ep} CFR^{T2}_{ep} P^{T2}_{ep} $$

Where,

* $T$ is the female cohort birth period which assume 3 intervals: T = {1925-39, 1940-54, 1955-69};
* $ep$ is the educational pairing profile, which assumes 16 possible combinations of female and male educational levels (F,M): ep = {(LP,LP), (LP,P), (LP,S), (LP,T), (P,LP), (P,P),
(P,S), (P,T), (S,LP), (S,P), (S,S), (S,T), (T,LP), (T,P), (T,S), (T,T)};
* $P^T_{ep}$ is the proportion of couples of female cohort T in educational pairing with an $ep$ profile.

The cohort fertility differences will be computed pairwise: between female cohorts born in 1925-39 and 1940-54, between 1940-54 and 1955-69 cohorts  and between 1925-39 and 1955-69 cohorts. These cohort fertility differentials can be decomposed in compositional effects of marriage markets, which are given by the prevalences of educational pairings, and rate effects, which are given by the educational pairing-specific CFRs (see @dasgupta1993 [p. 37] for details on decomposition of rates as functions of two vector-factors). Therefore:

$$ \Delta CFR_{1,2} = \Delta CFR_{1,2}^{\text{effect}} + \Delta P_{1,2}^{\text{effect}} $$

Then, we can evaluate compositional differences in terms of changig union educational profiles among female cohorts and differences intrinsic to falling CFRs among each educational profile of couples.

# Results

## CFR trends in Brazil 

Figure 1 presents trends of cohort fertility rates (CFRs) for married/in-union female cohorts by educational pairing profile for Brazil and the three grouped regions. Each panel has a fix educational level for the female partner and varying educational level for the male partner illustrated by different linetypes. 

For Brazil, both male and female schooling present marked reproductive differentials for the different cohorts. For older cohorts, couples with at least one partner in the least educated category presented cohort fertility rates much higher than the others. That distance among educational categories gets shorter through female cohorts for both males and females. This converging trend is an effect of unplanned institutional changes in Brazil guided by socioeconomic and cultural changes, urbanization and difusion of Western fertility behavior among lower educated social groups [@faria1989;@martine1996;@faria1997;@caldwell2006;@berquo_cavenaghi2014].

The distances among lines in the same graph are interpreted as the influence of male schooling in the couple's reproductive behavior. The higher level observed for older female cohorts with partners of the lowest educated category show the negative effect of low schooling of males in the past for the process of fertility transition. It is evident that increasing female education among cohorts minimizes differences of CFR among partner's educational categories. Therefore, female education guarantees women with higher bargaing power in family size decision making [@jejeebhoy1995] which results in a reproductive profile less attached to its husband educational characteristics and more related to females own socioeconomic status and perceived opportunity costs of reproduction [@becker1993].

Further, reduction of distances among curves through cohort evolution, verified for all levels of female education category, enphasizes the increase of female autonomy even for women of reduced schooling. Two elements must explain this reduction in differentials: 1) the lowest educational category encompasses analphabet people and people with some primary education, therefore, this shortening distances of curves are a natural movement of reduction of analphabetism among population [@figoli2006] which by itself contributes for increasing reproductive control [@jejeebhoy1995]; 2) the medicalization of female population through decades of 1970-1990 [@faria1989;@martine1996;@faria1997] and also the influence of Brazilian soap operas [@faria_potter1999;@laferrara_etal2012] promoted changes in social and cultural normas and brought more access to information on reproductive control providing more reproductive autonomy even for females of vulnerable social groups.

In regard to regional series each regional groupings presented a distinguished profile. Central-West region presented a conjugal CFR transition similar to the one observed for the country as a whole. In this region, male scholing has a stronger influence for women of lower schooling level of older cohorts. Additionally, as women of the region achieved higher schooling levels, the partner's educational differentials got smaller and CFRs get closer to replacement fertility levels. Younger cohorts exhibit CFRs similar for all educational categories of the partner going towards replacement levels. For females that have not completed primary school, we observed a converging trend among the male partner's educational levels, especially for cohorts born after 1940s.

North and Northeast regions started their conjugal CFRs transitions from values above 7 children per women for lower educated groups. In these regions, male partner's fertility differentials were abserved among all educational categories, especially for the transitions from uncompleted to completion of primary school. Further, in these areas the increase of females educational levels is accompanied by a reduction in fertility levels but does not eliminates the partner's educational differentials. Therefore, in these regions, female reproductive autonomy seems to be lower or there are lower opportunity costs to fertility control [@becker1993;@jejeebhoy1995]  and the partner's education acts as an important driver of fertility levels through a higher involvement of educated males in family planning decisions [@oliveira_etal2002]. Furthermore, the converging trends of fertility levels of pairings with lower educated males is not observed in these areas (figure 2). A possible explanation is that these regions suffered from a slow integration to the new urban-industrial economy that is established in São Paulo due to its export-agricultural roots and ruling local elites [@singer1973;@merrick_graham1981]. In this sense, we observe lower formal labor market engagement of women in these areas [@goncalves_etal2004;@barbosa2014] which result in lower social constraints to reproduction [@patarra_oliveira1988]. We may say North and Northeast were under influence of a patriarchal family model [@aguiar2000] with lower participation of women in the public sphere of society which inccurred in lower autonomy in family planning and hence in a higher fertility level [@becker1993;@folbre1994].

South and Southeast areas start their conjugal cohort fertility transition from lower levels than other areas of the country - less than 6 children per women for least educated groups. Male partner differentials are small even for women with complete primary school. In this regions, the observed convergence of CFRs for pairings with male partner without primary education complete to other pairings started for female cohorts born before 1930 as can be seen by the declining curve in the first panel of figure 2. This is a result of school expansion (redection of analphabetism) and transition of economic model to the urban-industrial model, centered in São Paulo area, which demanded more educated labor force and female participation in the labor market. Also, these regions received large shares of European migration from 1850 on-wards, from areas in which fertility levels were already at lower rates [CITAR]. For women with secondary schooling or more, younger cohorts show below replacement fertility levels independently of the partner's educational level.

## CFR decomposition


# Conclusions

# References